export function helpText(): string {
  return [
    "usage: sat [command] [options]",
    "",
    "commands:",
    "  history  Show answered question attempts",
    "  stats    Show progress stats, streak, and activity",
    "  weak     Show weak skills from recorded attempts",
    "  focus    Show current practice focus",
    "  review   Practice missed and corrected questions in the TUI",
    "",
    "history filters:",
    "      --wrong       Show currently missed questions",
    "      --corrected   Show corrected questions",
    "      --limit N     Limit rows",
    "      --since WHEN  Show rows since an ISO date, 7d, or 2w",
    "",
    "options:",
    "  -p, --pretty    Use colorized human-readable output",
    "      --json      Output JSON",
    "      --no-color  Disable ANSI color in pretty output",
    "  -V, --version   Show version",
    "  -h, --help      Show this help",
    "",
    "Run `sat` with no command to open the interactive TUI.",
  ].join("\n");
}
